name: CD pipleine
on:
  workflow_run:
    workflows: ["CI part to push the dockerhub"]
    types:
      - completed

jobs:
  build:
  
    runs-on: self-hosted
    steps:
      - name: down the docker container is live
        run: docker new1 down || true
      - name: pull the docker image
        run: docker pull dineth123412/news1:latest
      - name: keep only 5 newest docker images
        shell: bash
        run: |
          mapfile -t old_images < <(docker images -q | awk 'NR > 5')
          if [ ${#old_images[@]} -gt 0 ]; then
            docker rmi "${old_images[@]}" || true
          else
            echo "No old images to delete."
          fi
      - name: run the docker container
        run: docker run -d -p 5000:5000 dineth123412/news1:latest

      
      