name: CI part to push the dockerhub
on:
  push:
    branches:
      - main

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set image tag
        run: echo "IMAGE_TAG=$(( (GITHUB_RUN_NUMBER - 1) % 5 + 1 ))" >> $GITHUB_ENV

      - name: Docker Build
        run: |
          docker build \
            -t dineth123412/news1:${IMAGE_TAG} \
            -t dineth123412/news1:latest .

      - name: docker login and push
        run: |
          docker login -u dineth123412 -p ${{secrets.DOCKER}}
          docker push dineth123412/news1:${IMAGE_TAG}
          docker push dineth123412/news1:latest
      